### ISSUE TITLE
Should we make this a "Real" Thing...?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/ac#2]
- https://domainr.com/word.sy?gl=gb&q=wordsy
- https://domainr.com/?gl=gb&q=wurdi

![domain-vocabus](https://cloud.githubusercontent.com/assets/194400/7246107/b9b875aa-e7ef-11e4-9885-cc7f9bf3fc4e.png)

![domain-wordsy](https://cloud.githubusercontent.com/assets/194400/7246106/b9b3f674-e7ef-11e4-9234-ad867955b081.png)

![domain-mywords](https://cloud.githubusercontent.com/assets/194400/7246105/b9b3615a-e7ef-11e4-9379-d56236c7aeea.png)

![domain-aword](https://cloud.githubusercontent.com/assets/194400/7246104/b9b06efa-e7ef-11e4-8942-094f0985c2c9.png)

**Comment by iteles** [comment]
Oh, I like **word.sy**. I don't think the domain name is crazy important for this one, but word.sy is a great name!
[**time MVP**](https://github.com/ideaq/time) first though :wink:

**Comment by nelsonic** [comment]
http://venturebeat.com/2011/07/05/zynga-paid-53-3m-to-buy-words-with-friends-mobile-game-maker-newtoy/

**Comment by nelsonic** [comment]
€676/year ... https://shop.gandi.net/en/domain/suggest?search=word&tld=sy
![675-year](https://user-images.githubusercontent.com/194400/110801838-85a68780-8275-11eb-906b-2ec7243dda41.png)

Only worth it with a clear business plan. 💸
